version: '2'

services:
  hapi:
    build:
      context: ./
      dockerfile: ./dockerfiles/hapi
    links:
      - db:db
    ports:
      - 80:80
    volumes:
      - ./:/usr/src/app
    env_file: .env

  db:
    image: tutum/mongodb
    environment:
      - AUTH=no

  tests:
    build:
      context: ./
      dockerfile: ./dockerfiles/tests
    links:
      - hapi:hapi
    volumes:
      - ./:/usr/src/app

  dbload:
    image: tutum/mongodb
    links:
      - db:db
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: >
      mongoimport
      --collection users
      --db bank
      --drop
      --file ./misc/bank_db.json
      --host db

  dbtest:
    image: tutum/mongodb
    links:
      - db:db
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/bash

  node:
    image: node
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/bash
    
  vim:
    build:
      context: ./
      dockerfile: ./dockerfiles/vim
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
